### ISSUE TITLE
输入图像格式

### ISSUE THREAD

**Issue by LeonSakura** [cuiziteng/ECCV_RAW_Adapter#2]
崔博士您好，感谢您精彩的工作。在看您开源的代码时有一些疑问，在论文中提到分割任务的输入是用Invertible ISP生成的raw图，但根据开源的代码（ade.py和Raw adapter中block.py）来看，在分割任务时的输入好像是三通道的jpg图像，您能否给出一个简要的数据集结构说明嘛？（类似下图）
![Snipaste_2024-10-22_10-44-08](https://github.com/user-attachments/assets/a78d82cd-5fc1-467b-a236-ed04b05812a2)
期待您的回复
万分感谢！

**Comment by cuiziteng** [comment]
非常感谢您的疑问和兴趣，这部分是通过InvISP生成的raw-RGB图像，其实和真实的camera-RAW还是有着很大差距。我们这里更多是希望顺便验证一下我们RAW-Adapter在分割task下的有效性。

在做论文第一版实验的时候没有找到合适的RAW segmentation dataset，所以这里只能用InvISP生成的raw-RGB来做辅助验证，确实会和真实的RAW存在一些gap，可以理解为经过demosaic的RAW图像。

**Comment by LeonSakura** [comment]
好的感谢您的回复！
